"""
Gemini Agent: Responsible for orchestrating the complete workflow

① User Question
    ↓
② Gemini determines intent, decides which tool to call / what parameters to generate (function calling)
    ↓
③ Python executes the corresponding Dune API call
    ↓
④ On-chain data is retrieved
    ↓
⑤ Data is fed back to Gemini as a function_response
    ↓
⑥ Gemini analyzes and generates the final natural language answer
"""
import json

import google.generativeai as genai

from config import GEMINI_API_KEY, GEMINI_MODEL
from tools import TOOLS, TOOL_DISPATCH

genai.configure(api_key=GEMINI_API_KEY)

SYSTEM_INSTRUCTION = """You are an on-chain data analysis assistant.
When a user asks a question about a wallet address, contract, or on-chain activity:
1. Determine whether on-chain data needs to be queried.
2. If needed, select the appropriate tools (get_wallet_balances / get_wallet_transactions /
   get_token_transfers / run_dune_sql_query) and provide the correct parameters:
   - If the user specifies a natural language time range (e.g., "past 7 days") and precise aggregated statistics are required,
     prefer run_dune_sql_query (provided a corresponding query_id exists).
   - If you just want to view recent raw records, use get_wallet_transactions / get_token_transfers directly.
3. After receiving the data returned by the tool, please provide a clear and structured analysis conclusion in Simplified Chinese:
   - Summarize key metrics (number of transactions, amounts, tokens/contracts involved, etc.)
   - Point out anomalies or notable patterns
   - Give concise conclusions rather than just listing raw JSON data.
"""


class DuneGeminiAgent:
    def __init__(self):
        self.model = genai.GenerativeModel(
            model_name=GEMINI_MODEL,
            tools=TOOLS,
            system_instruction=SYSTEM_INSTRUCTION,
        )
        self.chat = self.model.start_chat(enable_automatic_function_calling=False)

    def ask(self, user_question: str, max_tool_rounds: int = 5) -> str:
        """
        Runs through the complete workflow from ① to ⑥, returning the final natural language analysis generated by Gemini.
        """
        response = self.chat.send_message(user_question)

        for _ in range(max_tool_rounds):
            function_calls = self._extract_function_calls(response)
            if not function_calls:
                # The model no longer requests tools, meaning it has provided the final text response
                break

            tool_result_parts = []
            for fc in function_calls:
                name = fc.name
                args = dict(fc.args) if fc.args else {}
                print(f"[Gemini requested tool call] {name}({args})")

                try:
                    result = TOOL_DISPATCH[name](**args)
                except Exception as e:  # Feed error information back to the model instead of crashing directly if a tool fails
                    result = {"error": str(e)}

                # Prevent Dune from returning excessively large data volumes that overflow the context, add a truncation safeguard
                result_json = json.dumps(result, default=str, ensure_ascii=False)
                if len(result_json) > 15000:
                    result_json = result_json[:15000] + "...(Data truncated)"

                tool_result_parts.append(
                    genai.protos.Part(
                        function_response=genai.protos.FunctionResponse(
                            name=name,
                            response={"result": result_json},
                        )
                    )
                )

            response = self.chat.send_message(
                genai.protos.Content(parts=tool_result_parts)
            )

        return response.text

    @staticmethod
    def _extract_function_calls(response):
        calls = []
        for cand in response.candidates:
            for part in cand.content.parts:
                if part.function_call and part.function_call.name:
                    calls.append(part.function_call)
        return calls